/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Maulana Yusuf S
 */
public class KonversiSuhu_Ahmad extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu_Ahmad
     */
    float celcius,

    /**
     * Creates new form KonversiSuhu_Ahmad
     */
    reamur, 

    /**
     * Creates new form KonversiSuhu_Ahmad
     */
    fahrenheit, 

    /**
     * Creates new form KonversiSuhu_Ahmad
     */
    kelvin;

    public KonversiSuhu_Ahmad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KonversiSuhu = new javax.swing.JLabel();
        Celcius = new javax.swing.JLabel();
        Reamur = new javax.swing.JLabel();
        Fahrenheit = new javax.swing.JLabel();
        Kelvin = new javax.swing.JLabel();
        tfCelcius = new javax.swing.JTextField();
        tfReamur = new javax.swing.JTextField();
        tfFahrenheit = new javax.swing.JTextField();
        tfKelvin = new javax.swing.JTextField();
        btnKonversi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KonversiSuhu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        KonversiSuhu.setForeground(new java.awt.Color(0, 0, 153));
        KonversiSuhu.setText("KONVERSI SUHU");

        Celcius.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Celcius.setText("Celcius (C)");

        Reamur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Reamur.setText("Reamur (R)");

        Fahrenheit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fahrenheit.setText("Fahrenheit (F)");

        Kelvin.setText("Kelvin (K)");

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KonversiSuhu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Celcius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKonversi))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fahrenheit)
                            .addComponent(Kelvin)
                            .addComponent(Reamur))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfReamur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFahrenheit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKelvin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(KonversiSuhu)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reamur)
                    .addComponent(tfReamur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celcius)
                    .addComponent(Fahrenheit)
                    .addComponent(tfCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kelvin)
                    .addComponent(tfKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKonversi))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // Tombol Konversi
        celcius = Float.parseFloat(tfCelcius.getText());
        reamur = (float) (0.8 * celcius);
        fahrenheit = (float) ((1.8 * celcius) + 32);
        kelvin = (float) (celcius + 273.15);

        tfReamur.setText("" + reamur);
        tfFahrenheit.setText("" + fahrenheit);
        tfKelvin.setText("" + kelvin);

    }//GEN-LAST:event_btnKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu_Ahmad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu_Ahmad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu_Ahmad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu_Ahmad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu_Ahmad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celcius;
    private javax.swing.JLabel Fahrenheit;
    private javax.swing.JLabel Kelvin;
    private javax.swing.JLabel KonversiSuhu;
    private javax.swing.JLabel Reamur;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JTextField tfCelcius;
    private javax.swing.JTextField tfFahrenheit;
    private javax.swing.JTextField tfKelvin;
    private javax.swing.JTextField tfReamur;
    // End of variables declaration//GEN-END:variables
}
